### PR TITLE
Sensor Library - TMP006

### PR DESCRIPTION
**Pull request by JLefebvre55**
Test Script Author: Angus Wu @AngusWu25 
Current Hardware Owner: Rosalie Pampolina @rosalie1612 
Final Review: Urmil Modi @urmilmodi 

1. Author reviews library contents
2. Jayden Lefebvre writes Arduino test script using library
2. Current owner tests library implementation on hardware, documents results

Comment on this PR if you have any questions

### CODE REVIEW

**Comment by angusjhwu** [comment]
Regarding the comment in TMP006.cpp line 11 "//TODO is tmp006.wake()", the sensor library's init function already wakes the sensor. So unless the sensor is instructed to head into sleep mode during operation, there is no need to implement the wake function. 
Other than that, the core function of the header and cpp files are ready for testing. The calibration factor can be implemented later.

**Comment by JLefebvre55** [comment]
@AngusWu25 Thanks for the clarification!

**Comment by rosalie1612** [comment]
The TMP006 sensor works as expected and it outputs the current temperature as shown in the attached image.
Screen Shot 2021-05-30 at 1 05 35 PM

**Review by rosalie1612 — APPROVED** [review]
The sensor works as expected and outputs the current temperature as shown in the attached image.
Screen Shot 2021-05-30 at 1 05 35 PM

**Comment by JLefebvre55** [comment]
@urmilmodi Awaiting your review

**Review by urmilmodi — APPROVED** [review]

**Pull request merged**
